services:
  web:
    image: ghcr.io/TU-ORG/TU-APP:staging
    env_file: .env.staging
    ports: ["8080:8080"]
    depends_on: [db]
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
