name: PR Policy

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review, labeled, unlabeled]
  pull_request_review:
    types: [submitted, edited, dismissed]
  issue_comment:
    types: [created]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  gate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Policy checks
        shell: bash
        env:
          EVENT: ${{ github.event_name }}
          IS_DRAFT: ${{ github.event.pull_request.draft || false }}
          LABELS_JSON: ${{ toJson(github.event.pull_request.labels || '') }}
        run: |
          echo "Event: ${EVENT}"
          if [ "${IS_DRAFT}" = "true" ]; then
            echo "::notice::PR es draft; permitiendo continuar sin bloquear."
            exit 0
          fi
          # Requisito mínimo: al menos 1 label
          if [ -z "${LABELS_JSON}" ] || ! echo "${LABELS_JSON}" | grep -q '"name"'; then
            echo "::error::Añade al menos 1 label al PR."
            exit 1
          fi
          echo "PR Policy OK"
