name: PR Policy
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  gate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Gate
        run: |
          set -euo pipefail
          echo "policy ok"
