name: Security Pipeline
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Semgrep (PR no-op)
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "semgrep skipped on PR; real run on push to main"
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Semgrep Scan
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: returntocorp/semgrep-action@v1

  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Trivy (PR no-op)
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "trivy skipped on PR; real run on push to main"
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Trivy FS
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true

  zap_baseline:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP (PR no-op)
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "ZAP skipped on PR; real run on push to main"
      - name: ZAP Baseline Scan
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ secrets.STAGING_URL }}
          rules_file_name: 'security/zap/.zap/rules.tsv'
          cmd_options: "-a"
      - name: Subir reporte ZAP
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html